name: insta_clone
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_icons: ^1.0.0+1
  camera: ^0.5.7+4
  flutter_spinkit: "^4.1.2"
  path_provider: ^1.6.5
  path: ^1.6.4
  video_player:
  image_picker:
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+2
  cloud_firestore: ^0.13.4+2


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
  assets:
   - images/

  fonts:
    - family: Billa
      fonts:
        - asset: fonts/Billabong.ttf
    
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
